### ISSUE TITLE
respond to pong-bot commands when offline

### ISSUE THREAD

**Issue by pust777** [kregnax/five-man-bot#25]
respond to pong-bot commands when  offline

**Comment by kregnax** [comment]
Could you clarify what you mean? You want FMB to respond to pong_bot commands?

**Comment by pust777** [comment]
Exactly that, but respond only when pong is offline, and specifically to inform the user that pong isn't available.

**Comment by pust777** [comment]
REMINDER[https://github.com/Rapptz/RoboDanny/blob/e7a0f81e5117bb5dd5183de2d2d2f93f88fc3841/cogs/profile.py#L13](url)

**Comment by pust777** [comment]
@kregnax closing this thing because of the voice thing
